//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kommentarer
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int UserID { get; set; }
        public int AntalTimmar { get; set; }
        public string Kommentar { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ProjektItem ProjektItem { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
