//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjektItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjektItem()
        {
            this.Kommentarers = new HashSet<Kommentarer>();
        }
    
        public int ID { get; set; }
        public int ProjektID { get; set; }
        public string Name { get; set; }
        public int UserID { get; set; }
        public int UtveckladeTimmar { get; set; }
        public int TotalTid { get; set; }
        public System.DateTime Deadline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kommentarer> Kommentarers { get; set; }
        public virtual Projekt Projekt { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
