//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUser()
        {
            this.Kommentarers = new HashSet<Kommentarer>();
            this.ProjektItems = new HashSet<ProjektItem>();
        }
    
        public int ID { get; set; }
        public int ProjektID { get; set; }
        public string Username { get; set; }
        public string SaltedPassword { get; set; }
        public bool IsAdmin { get; set; }
        public string Email { get; set; }
        public int Target_Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kommentarer> Kommentarers { get; set; }
        public virtual Projekt Projekt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjektItem> ProjektItems { get; set; }
    }
}
